name: 🧹 Chore Task
description: Create a chore task for SyntaxUI
title: '[🧹 Chore]: '
labels: chore

body:
  - type: markdown
    attributes:
      value: |
        **Is your chore task related to a problem? Please describe.**
        A clear and concise description of what the problem is. Ex. "I'm always frustrated when..."

  - type: input
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Explain the solution

  - type: input
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've thought about.
      placeholder: Alternative solutions

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Ansub/SyntaxUI/blob/main/CONTRIBUTING.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
